---
title: "Conclusion"
---
In our statistical analysis using the linear regression model we see that political party identification does have a significant affect on a person's view of the dangers of global warming. We see that as a person moves down the scale towards "Strong Republican" they view global warming as less dangerous. After including the variable education in our analysis we can see that education does have an affect on a persons view of the danger of global warming. This is explained by the fact that there are educated people in each category of political identification. The more education a person has the more likely they are too see global temperature raises as harmful. Even though there is some association between the two variables we see that political identification is still a more influential variable. We also see that income does not exibit a significant influence on a person's belief in the dangers of global warming. 

With this information we can form a targeted strategy to get the people who do not view global warming as a threat to realize the imminent danger in store for us. Since it is primarily the conservative side of the political party identification scale who do not think global warming is in issue we can start by showing them the negative consequences that Republicans care about. We can show them the job loss and intellectual property loss that will occur when we stop investing research and money into green infastructure.  Jobs will go overseas as political initiatives around the world make it easier for people to invest in green technology. Perhaps this will wake the American public up to the importance of investing in our planet's future.  