---
title: "The Global Crisis"
---

Hello, welcome to my website. This site is dedicated to exploring views of the American public on the dangers of global climate change.  Our planet is in danger, and it is important to make the nation aware of the importance of stopping the global destruction we are causing before it is too late. Our dear President Trump is doing everything in his power to ensure that the fight against global warming gets put on the back burner while we focus on America first initiatives. I can see the appeal of wanting to "see" the results of our efforts and focus on things that have an immediate effect, but ignoring our planets destruction is going to have detrimental consequences for everyone. 

For the past million years Earth has oscillated between periods of warm weather and ice ages. We are currently in a warming trend, however that trend has been drastically exacerbated by human activity. The accelerated accumulation of greenhouse gases in our atmosphere is caused by human activity, mainly the burning of fossil fuels to produce electricity. The United States is the world's second largest emitter of carbon dioxide. The effects of rapid increase in global temperature will include, rising sea levels, unpredictable weather, more natural disasters, decrease in air quality, and loss of food supply. 

As the temperature rises, glaciers will melt contributing to a global rise in sea level. Glaciers are disappearing NOW. For example, Glacier National Park used to have 150 glaciers within it, today there are 26. As sea levels rise, millions of people will be displaced from their homes. Historically, large cities are concentrated near the ocean, which will all be underwater when the glaciers have melted. Also, receding glaciers produce large icebergs, which will affect the boating industry and logistical operations. We will also see an increase in frequency and intensity of natural disasters. Droughts, fires, heat waves, hurricanes, floods, and earthquakes will all increase with continued global warming costing billions of dollars. Our food supply will also suffer as global warming intensifies. The onslaught of natural disasters will have an effect on farmable land, but also trees are flowering sooner than they should leading to a decrease in production. 

We need to focus our energy on mitigating the negative consequences of our actions by focusing on initiatives that reduce our carbon emissions and spend money on new green technology. Unfortunately, President Trump has decided to do the exact opposite. He has cut funding to scientific research and environmental programs. He is shrinking or eliminating national monuments in order to grant oil and gas companies access to the land. He has cut the Environmental Protection Agency's budget by 31% (more than any other federal agency). He hired Scott Pruitt to head the EPA. He is allowing the EPA to control and manipulate web content regarding these issues. Additionally, and arguably most detrimental, is his decision to leave the Paris Climate Agreement. 

In this agreement, the United States pledged to cut greenhouse gas emissions 26%-28% below the levels they were in 2005 by 2025. We also pledged $3billion in aid to poorer countries to help them achieve reduction in greenhouse gas emissions as well. By pulling out of this agreement, President Trump's ignorance will not only destroy our planet, but isolate the United States from the rest of the world. As the rest of the world shifts focus towards green technology the United States will be left without allies and without a competitive workforce. Fortunately, pulling out of this deal will take four years. So we need to wake up the American public to the dangers of this current president and ensure he does not get re-elected! 
